language: python
python:
- 2.7
install:
- echo "${GCLOUD_SERVICE_ACCOUNT_KEY}" > $HOME/service-account.json
- wget -O $HOME/google_appengine.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.91.zip
- unzip -q $HOME/google_appengine.zip -d $HOME
- pip install NoseGAE
script:
- nosetests --with-gae --gae-lib-root $HOME/google_appengine
deploy:
  provider: gae
  project: allow-any-origin-hrd
  keyfile: $HOME/service-account.json
