sudo: false
language: python
python:
- 2.7
before_install:
- openssl aes-256-cbc -K $encrypted_b953cba9cd01_key -iv $encrypted_b953cba9cd01_iv
  -in account.json.enc -out account.json -d
install:
- wget -O $HOME/google_appengine.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.28.zip
- unzip -q $HOME/google_appengine.zip -d $HOME
- pip install NoseGAE
script:
- nosetests --with-gae --gae-lib-root $HOME/google_appengine
deploy:
  provider: gae
  keyfile: account.json
  default: true
  project: allow-any-origin-hrd
