application: allow-any-origin-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  mime_type: image/vnd.microsoft.icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /
  static_files: static/index.html
  mime_type: text/html;charset=utf-8
  upload: static/index\.html

- url: /.*
  script: proxy.application
